# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MediaGoom
email: info@mediagoom.com
description: > # this means to ignore newlines until "baseurl:"
  MediaGoom. 
  Essential Web Streaming. 
  Providing the open source community with Web Streaming
  tools for mpeg-dash, hls and DRM.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mediagoom.com" # the base hostname & protocol for your site
twitter_username: mediagoom
github_username:  mediagoom

permalink: /blog/:title

# Build settings
markdown: kramdown
collections:
 - startsteps
